#cloud-config
users:
  - default
  - name: iacuser
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCemER4vOJBuocl26U+CaPW/tJzYZYubhVN13cuNK+7BOc6qbrhDOERUFSPLIOW25AbdcpwRaYTm6WzZfigbZeV3QEDbaMilR368DDit8QaI8ngm8fp+oEzyl9uy5UDYCSrpJxhF5l66QQ1UxNeIfVyPZirTs6JRK6mlUEJxx0iGq/b8LMEi6vMXN/f3XNI8/2bgz34PWoz/oq+FxQuSQcP8Qp5wyd3EWPpOmrY97N63eG9gFyk7EoBPTeUe/qbTcELMXAlBOc6Se4MCQu8i24Iq2GmdH2/BdORc3C8HAj9Avn3MSjbVEW0505nZBblkqYEM39p1TmM1q2o10ynOk/xCoh6ZjCXH2Lotlna3L1Bvje4FkJQAsbPvI8o6GqpKZUdA5FY9QhmvJ3OiNADP115D1TdNDhBplUFuULX5CoFZPTSgj54N50Nz4GSKAHneRVxcXz/KNcjpMgpwCLhLUOkRKHcL0OG6MM/zyzHe5P6KpFLhaZFqmzd8YL4I7KPT2bxcU+QbQaxxPlGK50gOXq4pCHACMFcQ2halPMeQfzFAN3cTle23OQYhIQZEPXnc+tG02Anwh00GjMXnvzjAwbpQpXH+dnEgKIjma4qvkstmG6yk2VLqqX4BJndE6/AWnkS6Ux5YU1aG5Zy+3uX+t95NDHC3WeHcPIoe4AIuvVbwQ== student@DESKTOP-1NUD89T

write_files:
  - path: /home/iacuser/.ssh/id_rsa_azure.pub
    content: |
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCemER4vOJBuocl26U+CaPW/tJzYZYubhVN13cuNK+7BOc6qbrhDOERUFSPLIOW25AbdcpwRaYTm6WzZfigbZeV3QEDbaMilR368DDit8QaI8ngm8fp+oEzyl9uy5UDYCSrpJxhF5l66QQ1UxNeIfVyPZirTs6JRK6mlUEJxx0iGq/b8LMEi6vMXN/f3XNI8/2bgz34PWoz/oq+FxQuSQcP8Qp5wyd3EWPpOmrY97N63eG9gFyk7EoBPTeUe/qbTcELMXAlBOc6Se4MCQu8i24Iq2GmdH2/BdORc3C8HAj9Avn3MSjbVEW0505nZBblkqYEM39p1TmM1q2o10ynOk/xCoh6ZjCXH2Lotlna3L1Bvje4FkJQAsbPvI8o6GqpKZUdA5FY9QhmvJ3OiNADP115D1TdNDhBplUFuULX5CoFZPTSgj54N50Nz4GSKAHneRVxcXz/KNcjpMgpwCLhLUOkRKHcL0OG6MM/zyzHe5P6KpFLhaZFqmzd8YL4I7KPT2bxcU+QbQaxxPlGK50gOXq4pCHACMFcQ2halPMeQfzFAN3cTle23OQYhIQZEPXnc+tG02Anwh00GjMXnvzjAwbpQpXH+dnEgKIjma4qvkstmG6yk2VLqqX4BJndE6/AWnkS6Ux5YU1aG5Zy+3uX+t95NDHC3WeHcPIoe4AIuvVbwQ== student@DESKTOP-1NUD89T

# Install Docker prerequisites and Docker
packages:
  - ca-certificates
  - curl
  - gnupg
  - lsb-release

runcmd:
  # Add Docker's official GPG key
  - chown -R iacuser:iacuser /home/iacuser
  - chmod 400 ~/.ssh/id_rsa_azure.pub
  - mkdir -p /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg

  # Set up the repository
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

  # Install Docker Engine
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin

  # Add vm_user to the docker group
  - usermod -aG docker iacuser
