# This workflow validates the docker-compose.yml file.
# It runs on any push or pull request to the 'main' branch.

name: 1 - Docker Compose Lint

on:
  push:
    branches: [ "main" ]
    paths:
      - 'opdracht/ansible/docker-compose.yml' # Only run if files in 'docker/' change
  pull_request:
    branches: [ "main" ]
    paths:
      - 'opdracht/ansible/docker-compose.yml'

jobs:
  validate-docker-compose:
    name: Validate Docker Compose
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run docker-compose config
        # This command attempts to parse the file.
        # If it fails, the exit code will be non-zero, failing the job.
        run: docker-compose -f docker/docker-compose.yml config --quiet
